# Generated by Django 3.2.9 on 2021-11-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shiftbid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(blank=True, max_length=254)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('seniority_number', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftbid.shiftbid')),
            ],
        ),
    ]
