# Generated by Django 3.2.9 on 2021-11-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='agent_id',
            new_name='shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='seniority_number',
        ),
    ]
