# Generated by Django 3.2.9 on 2021-11-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbid', '0001_initial'),
        ('shift', '0002_auto_20211115_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftbid.shiftbid'),
        ),
    ]
