# Generated by Django 3.2.9 on 2021-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiftbid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=250, verbose_name='Report Name')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
